[package]
name = "buidl-rs"
version = "0.1.0"
authors = ["Paul Miller <paul@pauljmiller.com>"]
edition = "2018"

[dependencies]
rand = "0.4.3"
sha2 = "0.8.0"
rustc-serialize = "0.3.24"
arrayref = "0.3.5"

[dependencies.secp256k1]
version = "0.11.2"

features = ["rand"]